---
# tasks file for snapclient
- name: "Ensure the Snapcast client is installed"
  become: true
  apt:
    deb: "https://github.com/badaix/snapcast/releases/download/v{{ snapcast_version }}/snapclient_{{ snapcast_version}}_{{ snapcast_architecture}}.deb"
- name: "Ensure /var/lib/snapclient exists (to prevent runtime warnings)"
  become: true
  file:
    path: /var/lib/snapclient
    state: directory
    owner: snapclient
    group: audio
    mode: 0755
- name: "Ensure the options to the Snapclient daemon are set"
  become: true
  lineinfile:
    path: /etc/default/snapclient
    regexp: "^SNAPCLIENT_OPTS="
    line: "SNAPCLIENT_OPTS=\"{{ snapcast_client_daemon_options }}\""
