---
# tasks file for snapserver
- name: "Ensure the Snapcast server is installed"
  become: true
  apt:
    deb: "https://github.com/badaix/snapcast/releases/download/v{{ snapcast_version }}/snapserver_{{ snapcast_version}}{{ snapcast_version_suffix }}_{{ snapcast_architecture}}.deb"
