---
# tasks file for snapserver
- name: "Ensure the Snapcast server is installed"
  become: true
  apt:
    deb: "https://github.com/badaix/snapcast/releases/download/v{{ snapcast_version }}/snapserver_{{ snapcast_version}}{{ snapcast_version_suffix }}_{{ snapcast_architecture}}.deb"
- name: "Ensure the options to the Snapserver daemon are set"
  become: true
  lineinfile:
    path: /etc/default/snapserver
    regexp: "^SNAPSERVER_OPTS="
    line: "SNAPSERVER_OPTS=\"{{ snapcast_server_daemon_options }}\""
- name: "Set the Snapserver buffer"
  become: true
  lineinfile:
    dest: /etc/snapserver.conf
    regexp: "^buffer = "
    line: "buffer = {{ snapcast_server_buffer_ms }}"
    insertafter: "^# Buffer"
- name: "Configure the Snapserver sources"
  become: true
  lineinfile:
    dest: /etc/snapserver.conf
    regexp: "source = pipe:///tmp/snapfifo?name=default"
    line: "source = pipe:///tmp/snapfifo?name=default&sampleformat=44100:16:2"
